#include "main.h"

#include <platforms/STM32/platform.h>
#include <senders/GPIOSender_poll.h>


// NOTE: The HAL initialization functions auto-generated by the IDE have been
// omitted.

#define MSG_BIT_LEN 112
static const bool MSG_BITS[MSG_BIT_LEN] = {
    0, 1, 1, 1, 0, 1, 1, 1, 0,          1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
    0, 0, 1, 0, 1, 1, 0, 1, 0,          1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
    1, 0, 0, 1, 0, 1, 0, 1, 1,          0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
    1, 0, 0, 0, 1, 1, 0, 1, 1,          1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
    1, 0, 1, 0, 1, 1, 1, 0, 1,          0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
    0, 0, 1, 0, 0, 0, 0, 1, /*ACK:*/ 1, 1, 1, 1, 1, 1, 1, 1, 1};

int main(void) {
  // Init board
  HAL_Init();
  SystemClock_Config();
  MX_ICACHE_Init();
  MX_GPIO_Init();

  // CANflict Setup
  // Use PA1 as CANTX
  struct CANflict_GPIO_t tx_gpio;
  tx_gpio.port = GPIOA;
  tx_gpio.pin = GPIO_PIN_1;

  struct CANflict_SenderConf_t sndConf;
  sndConf.gpio = &tx_gpio;
  sndConf.cyclesBetweenBits = 2;

  CANflict_sender_init(&sndConf);

  // Send continuously
  while (1) {
    /* busy wait between messages */
    for (int i = 0; i < 1000000; ++i)
      ;
    CANflict_sender_setMsgToSend(&sndConf, MSG_BITS, MSG_BIT_LEN);
    CANflict_sender_sendMsg(&sndConf);
  }
}
